ALU_tb: \
	../PhaethonISA/Generated/PhaethonOpCode.v \
	ALU_tb.v \
	ALU.v \
	FloatingAdd.v \
	FloatingFromInt.v \
	FloatingMultiply.v \
	FloatingMultiplyAdd.v \
	FloatingCompare.v \
	FloatingDivide.v
	iverilog -o ALU_tb \
	ALU_tb.v \
	ALU.v \
	FloatingAdd.v \
	FloatingFromInt.v \
	FloatingMultiply.v \
	FloatingMultiplyAdd.v \
	FloatingCompare.v \
	FloatingDivide.v
	