ALU_tb: \
	../PhaethonISA/Generated/PhaethonOpCode.v \
	ALU_tb.sv \
	ALU.sv \
	FloatingAdd.sv \
	FloatingFromInt.sv \
	FloatingMultiply.sv \
	FloatingMultiplyAdd.sv \
	FloatingCompare.sv \
	FloatingDivide.sv
	iverilog -o ALU_tb \
	ALU_tb.sv \
	ALU.sv \
	FloatingAdd.sv \
	FloatingFromInt.sv \
	FloatingMultiply.sv \
	FloatingMultiplyAdd.sv \
	FloatingCompare.sv \
	FloatingDivide.sv
	